version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:5173"
  data_service:
    container_name: data_service
    build:
      context: ./backend/data_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data_service:/usr/src/app/data_service/src
    depends_on:
      - redis
  display_service:
    container_name: display_service
    build:
      context: ./backend/display_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend/display_service:/usr/src/app/display_service/src
    depends_on:
      - redis
  link_service:
    container_name: link_service
    build:
      context: ./backend/link_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/link_service:/usr/src/app/link_service/src
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
